
services:

  minio:
    image: quay.io/minio/minio:latest
    container_name: e-concours-minio
    restart: unless-stopped
    command: server /data --console-address ":9041"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9040:9000"
      - "9041:9001"
    volumes:
      - minio_data:/data
    networks:
      - e-concours-network

  redis:
    image: redis:7-alpine
    container_name: e-concours-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - e-concours-network


volumes:
  minio_data:
  redis_data:

networks:
  e-concours-network:
    driver: bridge